---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - digicloud.issuer.vamirreza.github.io
  resources:
  - digicloudclusterissuers
  - digicloudissuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - digicloud.issuer.vamirreza.github.io
  resources:
  - digicloudclusterissuers/finalizers
  - digicloudissuers/finalizers
  verbs:
  - update
- apiGroups:
  - digicloud.issuer.vamirreza.github.io
  resources:
  - digicloudclusterissuers/status
  - digicloudissuers/status
  verbs:
  - get
  - patch
  - update
