apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: digicloud-issuer-system
  labels:
    app.kubernetes.io/name: digicloud-issuer
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: digicloud-issuer
    app.kubernetes.io/part-of: digicloud-issuer
    app.kubernetes.io/managed-by: kustomize
