apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: digicdn-io-certificate
  namespace: cert-manager
spec:
  # The secret name where the certificate will be stored
  secretName: example-tls
  
  # Reference to the DigicloudIssuer
  issuerRef:
    name: digicloud-issuer
    kind: DigicloudIssuer
    group: digicloud.issuer.vamirreza.github.io
  
  # Common name for the certificate
  commonName: digicdn.io
  
  # DNS names for the certificate
  dnsNames:
  - digicdn.io
  - "*.digicdn.io"  # Wildcard subdomain support