name: Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'api/**'
      - 'examples/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'README.md'
      - 'docs/**'
      - 'api/**'
      - 'examples/**'

jobs:
  generate-docs:
    name: Generate API Documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Download dependencies
      run: go mod download

    - name: Install controller-gen
      run: go install sigs.k8s.io/controller-tools/cmd/controller-gen@latest

    - name: Generate API reference
      run: |
        mkdir -p docs/api
        controller-gen crd:generateEmbeddedObjectMeta=true paths="./api/..." output:crd:artifacts:config=config/crd/bases
        # Generate API documentation (you can add tools like gen-crd-api-reference-docs)

    - name: Validate examples
      run: |
        # Validate example YAML files
        find examples -name "*.yaml" -exec echo "Validating {}" \; -exec kubectl --dry-run=client apply -f {} \;

    - name: Check documentation links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
        use-verbose-mode: 'yes'
        config-file: '.github/markdown-link-check-config.json'

  deploy-docs:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    needs: generate-docs
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Pages
      uses: actions/configure-pages@v3

    - name: Build documentation site
      run: |
        mkdir -p _site
        cp README.md _site/index.md
        cp -r examples/ _site/
        cp -r config/ _site/
        # Add any additional documentation generation here

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v2
      with:
        path: '_site'

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
